#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
A Tool to assist in migrating an existing codebase from Saltarelle to TypeScript.  

MIT License

Copyright (c) 2022 Pangaea Information Technologies, Ltd.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import sys, re, os.path

### Global State Variables ###

_asm_name = ""              # The name to pass to "ss.initAssembly"
_namespaces = { "ss" }      # All defined namespaces corresponding to folders

def

### Helper Methods ###

### Main Method ###

if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise SystemExit("Usage: %s FOO" % sys.argv[0])

    [_, filename, foo, foo ] = sys.argv

    asmName = ""

